INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (1,'Electronics','Accessories & Supplies')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (2,'Electronics','Camera & Photo')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (3,'Electronics','Car & Vehicle Electronics')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (4,'Electronics','Cell Phones & Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (5,'Electronics','Computers & Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (6,'Electronics','GPS & Navigation')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (7,'Electronics','Headphones')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (8,'Electronics','Home Audio')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (9,'Electronics','Office Electronics')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (10,'Electronics','Portable Audio & Video')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (11,'Electronics','Security')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (12,'Electronics','Service Plans')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (13,'Electronics','Television & Video')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (14,'Electronics','Video Game Consoles & Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (15,'Electronics','Video Projectors')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (16,'Electronics','Wearable Technology')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (17,'Electronics','eBook Readers & Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (18,'Computers','Computers Accessories & Peripherals')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (19,'Computers','Computer Components')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (20,'Computers','Computers & Tablets')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (21,'Computers','Data Storage')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (22,'Computers','External Components')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (23,'Computers','Laptop Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (24,'Computers','Monitors')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (25,'Computers','Networking Products')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (26,'Computers','Power Strips & Surge Protectors')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (27,'Computers','Printers')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (28,'Computers','Scanners')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (29,'Computers','Servers')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (30,'Computers','Tablet Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (31,'Computers','Tablet Replacement Parts')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (32,'Smart Home','Smart Home Lighting')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (33,'Smart Home','Smart Locks and Entry')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (34,'Smart Home','Security Cameras and Systems')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (35,'Smart Home','Plugs and Outlets')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (36,'Smart Home','New Smart Devices')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (37,'Smart Home','Heating and Cooling')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (38,'Smart Home','Detectors and Sensors')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (39,'Smart Home','Home Entertainment')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (40,'Smart Home','Pet')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (41,'Smart Home','Voice Assistants and Hubs')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (42,'Smart Home','Kitchen')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (43,'Smart Home','Vacuum and Mops')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (44,'Smart Home','Lawn and Garden')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (45,'Smart Home','WIFI and Networking')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (46,'Arts & Crafts','Painting & Drawing')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (47,'Arts & Crafts','Beading & Jewelry Making')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (48,'Arts & Crafts','Crafting')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (49,'Arts & Crafts','Fabric')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (50,'Arts & Crafts','Fabric Decorating')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (51,'Arts & Crafts','Knitting & Crochet')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (52,'Arts & Crafts','Needlework')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (53,'Arts & Crafts','Organization, Storage & Transport')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (54,'Arts & Crafts','Printmaking')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (55,'Arts & Crafts','Sewing')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (56,'Arts & Crafts','Party Decorations & Supplies')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (57,'Arts & Crafts','Gift Wrapping Supplies')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (58,'Mens Fashion','Clothing')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (59,'Mens Fashion','Shoes')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (60,'Mens Fashion','Watches')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (61,'Mens Fashion','Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (62,'Womens Fashion','Clothing')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (63,'Womens Fashion','Shoes')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (64,'Womens Fashion','Watches')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (65,'Womens Fashion','Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (66,'Womens Fashion','Jewelry')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (67,'Womens Fashion','School Uniforms')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (68,'Movies & Television','Movies')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (69,'Movies & Television','TV Shows')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (70,'Movies & Television','Blu-ray')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (71,'Movies & Television','4K Ultra HD')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (72,'Movies & Television','Best Sellers')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (73,'Movies & Television','Todays Deals')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (74,'Movies & Television','New Releases')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (75,'Movies & Television','Pre-orders')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (76,'Movies & Television','Comic Book')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (77,'Movies & Television','Kids & Family')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (78,'Software','Accounting & Finance')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (79,'Software','Antivirus & Security')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (80,'Software','Business & Office')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (81,'Software','Childrens')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (82,'Software','Design & Illustration')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (83,'Software','Education & Reference')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (84,'Software','Games')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (85,'Software','Lifestyle & Hobbies')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (86,'Software','Music')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (87,'Software','Networking & Servers')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (88,'Software','Operating Systems')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (89,'Software','Photography')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (90,'Software','Programming & Web Development')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (91,'Software','Utilities')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (92,'Beauty','Makeup')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (93,'Beauty','Skin Care')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (94,'Beauty','Hair Care')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (95,'Beauty','Fragrance')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (96,'Beauty','Foot,Hand & Nail Care')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (97,'Beauty','Tools & Accessories')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (98,'Beauty','Shave & Hair Removal')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (99,'Beauty','Personal Care')
INSERT INTO Categories(CategoryID, CategoryType, CategoryName) VALUES (100,'Beauty','Oral Care')
